export interface QuarterlySheetRecord {
  "Reporting Month (mmm'yy)": string;
  "Child ID/ User ID [Provided by Insure Zeal]": string;
  "Insurer /broker code": string;
  "Policy Start Date": string;
  "Policy End Date": string;
  "Booking Date(Click to select Date)": string;
  "Broker Name": string;
  "Insurer name": string;
  "Major Categorisation( Motor/Life/ Health)": string;
  "Product (Insurer Report)": string;
  "Product Type": string;
  "Plan type (Comp/STP/SAOD)": string;
  "Gross premium": string;
  "GST Amount": string;
  "Net premium": string | null;
  "OD Preimium": string;
  "TP Premium": string;
  "Policy number": string;
  "Formatted Policy number": string;
  "Registration.no": string;
  "Make_Model": string;
  "Model": string;
  "Vehicle_Variant": string;
  "GVW": string;
  "RTO": string;
  "State": string;
  "Cluster": string;
  "Fuel Type": string;
  "CC": string;
  "Age(Year)": string;
  "NCB (YES/NO)": string;
  "Discount %": string;
  "Business Type": string;
  "Seating Capacity": string;
  "Veh_Wheels": string;
  "Customer Name": string;
  "Customer Number": string;
  "Commissionable Premium": string;
  "Incoming Grid %": string;
  "Receivable from Broker": string;
  "Extra Grid": string;
  "Extra Amount Receivable from Broker": string;
  "Total Receivable from Broker": string;
  "Claimed By": string;
  "Payment by": string;
  "Payment Mode": string;
  "Cut Pay Amount Received From Agent": string;
  "Already Given to agent": string;
  "Actual Agent_PO%": string;
  "Agent_PO_AMT": string;
  "Agent_Extra%": string;
  "Agent_Extr_Amount": string;
  "Agent Total PO Amount": string;
  "Payment By Office": string;
  "PO Paid To Agent": string;
  "Running Bal": string;
  "Total Receivable from Broker Include 18% GST": string;
  "IZ Total PO%": string;
  "As per Broker PO%": string;
  "As per Broker PO AMT": string;
  "PO% Diff Broker": string;
  "PO AMT Diff Broker": string;
  "As per Agent Payout%": string;
  "As per Agent Payout Amount": string;
  "PO% Diff Agent": string;
  "PO AMT Diff Agent": string;
  "Invoice Status": string;
  "Invoice Number": string;
  "Remarks": string;
  "Match": string;
  "Agent Code": string;
}

export interface AdvancedFilterOptions {
  search?: string;
  agent_code?: string;
  insurer_name?: string;
  policy_number?: string;
  reporting_month?: string;
  product_type?: string;
  payment_by?: string;
  invoice_status?: string;
  major_categorisation?: string;
  state?: string;
  broker_name?: string;
  booking_date_from?: string;
  booking_date_to?: string;
  gross_premium_min?: number;
  gross_premium_max?: number;
  net_premium_min?: number;
  net_premium_max?: number;
  // Date filters
  policy_start_date_from?: string;
  policy_start_date_to?: string;
  policy_end_date_from?: string;
  policy_end_date_to?: string;
  // Additional filters
  business_type?: string;
  fuel_type?: string;
  ncb?: 'YES' | 'NO';
  plan_type?: string;
  rto?: string;
  cluster?: string;
}