"""add_comprehensive_cutpay_fields_for_master_sheet

Revision ID: 07db71c72ff0
Revises: f17eb6a061b8
Create Date: 2025-06-27 16:15:53.324347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07db71c72ff0'
down_revision: Union[str, None] = 'f17eb6a061b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('formatted_policy_number', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('major_categorisation', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('product_insurer_report', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('product_type', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('plan_type', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('gross_premium', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('od_premium', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('tp_premium', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('registration_no', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('make_model', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('vehicle_variant', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('gvw', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('rto', sa.String(length=20), nullable=True))
    op.add_column('cut_pay', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('fuel_type', sa.String(length=20), nullable=True))
    op.add_column('cut_pay', sa.Column('cc', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('age_year', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('ncb', sa.String(length=10), nullable=True))
    op.add_column('cut_pay', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('business_type', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('seating_capacity', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('veh_wheels', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('reporting_month', sa.String(length=10), nullable=True))
    op.add_column('cut_pay', sa.Column('booking_date', sa.Date(), nullable=True))
    op.add_column('cut_pay', sa.Column('incoming_grid_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('extra_grid', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('commissionable_premium', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('payout_on', sa.String(length=20), nullable=True))
    op.add_column('cut_pay', sa.Column('agent_extra_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('payment_by_office', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('insurer_name', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('broker_name', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('insurer_broker_code', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('cluster', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('receivable_from_broker', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('extra_amount_receivable_from_broker', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('total_receivable_from_broker', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('total_receivable_from_broker_with_gst', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('agent_po_amt', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('agent_extra_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('total_agent_po_amt', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('claimed_by', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('already_given_to_agent', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('po_paid_to_agent', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('running_bal', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('match_status', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.alter_column('cut_pay', 'payment_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cut_pay', 'payment_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('cut_pay', 'invoice_number')
    op.drop_column('cut_pay', 'match_status')
    op.drop_column('cut_pay', 'running_bal')
    op.drop_column('cut_pay', 'po_paid_to_agent')
    op.drop_column('cut_pay', 'already_given_to_agent')
    op.drop_column('cut_pay', 'claimed_by')
    op.drop_column('cut_pay', 'total_agent_po_amt')
    op.drop_column('cut_pay', 'agent_extra_amount')
    op.drop_column('cut_pay', 'agent_po_amt')
    op.drop_column('cut_pay', 'total_receivable_from_broker_with_gst')
    op.drop_column('cut_pay', 'total_receivable_from_broker')
    op.drop_column('cut_pay', 'extra_amount_receivable_from_broker')
    op.drop_column('cut_pay', 'receivable_from_broker')
    op.drop_column('cut_pay', 'cluster')
    op.drop_column('cut_pay', 'insurer_broker_code')
    op.drop_column('cut_pay', 'broker_name')
    op.drop_column('cut_pay', 'insurer_name')
    op.drop_column('cut_pay', 'payment_by_office')
    op.drop_column('cut_pay', 'agent_extra_percent')
    op.drop_column('cut_pay', 'payout_on')
    op.drop_column('cut_pay', 'commissionable_premium')
    op.drop_column('cut_pay', 'extra_grid')
    op.drop_column('cut_pay', 'incoming_grid_percent')
    op.drop_column('cut_pay', 'booking_date')
    op.drop_column('cut_pay', 'reporting_month')
    op.drop_column('cut_pay', 'veh_wheels')
    op.drop_column('cut_pay', 'seating_capacity')
    op.drop_column('cut_pay', 'business_type')
    op.drop_column('cut_pay', 'discount_percent')
    op.drop_column('cut_pay', 'ncb')
    op.drop_column('cut_pay', 'age_year')
    op.drop_column('cut_pay', 'cc')
    op.drop_column('cut_pay', 'fuel_type')
    op.drop_column('cut_pay', 'state')
    op.drop_column('cut_pay', 'rto')
    op.drop_column('cut_pay', 'gvw')
    op.drop_column('cut_pay', 'vehicle_variant')
    op.drop_column('cut_pay', 'model')
    op.drop_column('cut_pay', 'make_model')
    op.drop_column('cut_pay', 'registration_no')
    op.drop_column('cut_pay', 'gst_amount')
    op.drop_column('cut_pay', 'tp_premium')
    op.drop_column('cut_pay', 'od_premium')
    op.drop_column('cut_pay', 'gross_premium')
    op.drop_column('cut_pay', 'customer_name')
    op.drop_column('cut_pay', 'plan_type')
    op.drop_column('cut_pay', 'product_type')
    op.drop_column('cut_pay', 'product_insurer_report')
    op.drop_column('cut_pay', 'major_categorisation')
    op.drop_column('cut_pay', 'formatted_policy_number')
    # ### end Alembic commands ###
