"""Add running_bal field to policies table

Revision ID: 23dbe9ec64db
Revises: 860543ed4b27
Create Date: 2025-08-01 19:36:51.492729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23dbe9ec64db'
down_revision: Union[str, None] = '860543ed4b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('running_bal', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'running_bal')
    # ### end Alembic commands ###
