"""init

Revision ID: 26b2701970ce
Revises: 
Create Date: 2025-11-13 22:28:03.593403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b2701970ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('rm', sa.String(length=100), nullable=False),
    sa.Column('gst', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_broker_code'), 'brokers', ['broker_code'], unique=True)
    op.create_index(op.f('ix_brokers_id'), 'brokers', ['id'], unique=False)
    op.create_table('insurers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurers_id'), 'insurers', ['id'], unique=False)
    op.create_index(op.f('ix_insurers_insurer_code'), 'insurers', ['insurer_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.Text(), server_default=sa.text('NULL::character varying'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('phone', name='users_phone_key')
    )
    op.create_table('admin_child_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_child_ids_child_id'), 'admin_child_ids', ['child_id'], unique=True)
    op.create_index(op.f('ix_admin_child_ids_id'), 'admin_child_ids', ['id'], unique=False)
    op.create_table('child_id_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('insurer_code', sa.String(length=10), nullable=False),
    sa.Column('broker_code', sa.String(length=10), nullable=True),
    sa.Column('preferred_rm_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['broker_code'], ['brokers.broker_code'], ),
    sa.ForeignKeyConstraint(['insurer_code'], ['insurers.insurer_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_id_requests_child_id'), 'child_id_requests', ['child_id'], unique=True)
    op.create_index(op.f('ix_child_id_requests_user_id'), 'child_id_requests', ['user_id'], unique=False)
    op.create_table('cutpay_agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_code', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=100), nullable=False),
    sa.Column('payment_mode_detail', sa.Text(), nullable=True),
    sa.Column('po_paid_to_agent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code', 'date', name='unique_cutpay_agent_config_per_date')
    )
    op.create_index('idx_cutpay_agent_config_agent_code', 'cutpay_agent_configs', ['agent_code'], unique=False)
    op.create_index('idx_cutpay_agent_config_date', 'cutpay_agent_configs', ['date'], unique=False)
    op.create_index(op.f('ix_cutpay_agent_configs_agent_code'), 'cutpay_agent_configs', ['agent_code'], unique=False)
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurer_name', sa.String(length=100), nullable=False),
    sa.Column('insurer_code', sa.String(length=50), nullable=True),
    sa.Column('total_records_processed', sa.Integer(), nullable=False),
    sa.Column('total_records_updated', sa.Integer(), nullable=False),
    sa.Column('new_records_added', sa.Integer(), nullable=False),
    sa.Column('reporting_month_variations', sa.Integer(), nullable=True),
    sa.Column('child_id_variations', sa.Integer(), nullable=True),
    sa.Column('insurer_broker_code_variations', sa.Integer(), nullable=True),
    sa.Column('policy_start_date_variations', sa.Integer(), nullable=True),
    sa.Column('policy_end_date_variations', sa.Integer(), nullable=True),
    sa.Column('booking_date_variations', sa.Integer(), nullable=True),
    sa.Column('broker_name_variations', sa.Integer(), nullable=True),
    sa.Column('insurer_name_variations', sa.Integer(), nullable=True),
    sa.Column('major_categorisation_variations', sa.Integer(), nullable=True),
    sa.Column('product_variations', sa.Integer(), nullable=True),
    sa.Column('product_type_variations', sa.Integer(), nullable=True),
    sa.Column('plan_type_variations', sa.Integer(), nullable=True),
    sa.Column('gross_premium_variations', sa.Integer(), nullable=True),
    sa.Column('gst_amount_variations', sa.Integer(), nullable=True),
    sa.Column('net_premium_variations', sa.Integer(), nullable=True),
    sa.Column('od_premium_variations', sa.Integer(), nullable=True),
    sa.Column('tp_premium_variations', sa.Integer(), nullable=True),
    sa.Column('policy_number_variations', sa.Integer(), nullable=True),
    sa.Column('formatted_policy_number_variations', sa.Integer(), nullable=True),
    sa.Column('registration_no_variations', sa.Integer(), nullable=True),
    sa.Column('make_model_variations', sa.Integer(), nullable=True),
    sa.Column('model_variations', sa.Integer(), nullable=True),
    sa.Column('vehicle_variant_variations', sa.Integer(), nullable=True),
    sa.Column('gvw_variations', sa.Integer(), nullable=True),
    sa.Column('rto_variations', sa.Integer(), nullable=True),
    sa.Column('state_variations', sa.Integer(), nullable=True),
    sa.Column('cluster_variations', sa.Integer(), nullable=True),
    sa.Column('fuel_type_variations', sa.Integer(), nullable=True),
    sa.Column('cc_variations', sa.Integer(), nullable=True),
    sa.Column('age_year_variations', sa.Integer(), nullable=True),
    sa.Column('ncb_variations', sa.Integer(), nullable=True),
    sa.Column('discount_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('business_type_variations', sa.Integer(), nullable=True),
    sa.Column('seating_capacity_variations', sa.Integer(), nullable=True),
    sa.Column('veh_wheels_variations', sa.Integer(), nullable=True),
    sa.Column('customer_name_variations', sa.Integer(), nullable=True),
    sa.Column('customer_number_variations', sa.Integer(), nullable=True),
    sa.Column('commissionable_premium_variations', sa.Integer(), nullable=True),
    sa.Column('incoming_grid_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('receivable_from_broker_variations', sa.Integer(), nullable=True),
    sa.Column('extra_grid_variations', sa.Integer(), nullable=True),
    sa.Column('extra_amount_receivable_variations', sa.Integer(), nullable=True),
    sa.Column('total_receivable_from_broker_variations', sa.Integer(), nullable=True),
    sa.Column('claimed_by_variations', sa.Integer(), nullable=True),
    sa.Column('payment_by_variations', sa.Integer(), nullable=True),
    sa.Column('payment_mode_variations', sa.Integer(), nullable=True),
    sa.Column('cut_pay_amount_received_variations', sa.Integer(), nullable=True),
    sa.Column('already_given_to_agent_variations', sa.Integer(), nullable=True),
    sa.Column('actual_agent_po_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('agent_po_amt_variations', sa.Integer(), nullable=True),
    sa.Column('agent_extra_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('agent_extra_amount_variations', sa.Integer(), nullable=True),
    sa.Column('agent_total_po_amount_variations', sa.Integer(), nullable=True),
    sa.Column('payment_by_office_variations', sa.Integer(), nullable=True),
    sa.Column('po_paid_to_agent_variations', sa.Integer(), nullable=True),
    sa.Column('running_bal_variations', sa.Integer(), nullable=True),
    sa.Column('total_receivable_gst_variations', sa.Integer(), nullable=True),
    sa.Column('iz_total_po_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('as_per_broker_po_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('as_per_broker_po_amt_variations', sa.Integer(), nullable=True),
    sa.Column('po_percentage_diff_broker_variations', sa.Integer(), nullable=True),
    sa.Column('po_amt_diff_broker_variations', sa.Integer(), nullable=True),
    sa.Column('actual_agent_po_percentage_2_variations', sa.Integer(), nullable=True),
    sa.Column('as_per_agent_payout_percentage_variations', sa.Integer(), nullable=True),
    sa.Column('as_per_agent_payout_amount_variations', sa.Integer(), nullable=True),
    sa.Column('po_percentage_diff_agent_variations', sa.Integer(), nullable=True),
    sa.Column('po_amt_diff_agent_variations', sa.Integer(), nullable=True),
    sa.Column('invoice_status_variations', sa.Integer(), nullable=True),
    sa.Column('invoice_number_variations', sa.Integer(), nullable=True),
    sa.Column('remarks_variations', sa.Integer(), nullable=True),
    sa.Column('match_variations', sa.Integer(), nullable=True),
    sa.Column('agent_code_variations', sa.Integer(), nullable=True),
    sa.Column('data_variance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reconciliation_reports_created_at', 'reconciliation_reports', ['created_at'], unique=False)
    op.create_index('idx_reconciliation_reports_insurer', 'reconciliation_reports', ['insurer_name'], unique=False)
    op.create_index('idx_reconciliation_reports_insurer_code', 'reconciliation_reports', ['insurer_code'], unique=False)
    op.create_index('idx_reconciliation_reports_processed_by', 'reconciliation_reports', ['processed_by'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_insurer_code'), 'reconciliation_reports', ['insurer_code'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_insurer_name'), 'reconciliation_reports', ['insurer_name'], unique=False)
    op.create_table('user_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=15), nullable=True),
    sa.Column('alternate_email', sa.String(length=255), nullable=True),
    sa.Column('permanent_address_line1', sa.String(length=200), nullable=True),
    sa.Column('permanent_address_line2', sa.String(length=200), nullable=True),
    sa.Column('permanent_city', sa.String(length=50), nullable=True),
    sa.Column('permanent_state', sa.String(length=50), nullable=True),
    sa.Column('permanent_pincode', sa.String(length=6), nullable=True),
    sa.Column('communication_same_as_permanent', sa.Boolean(), nullable=True),
    sa.Column('communication_address_line1', sa.String(length=200), nullable=True),
    sa.Column('communication_address_line2', sa.String(length=200), nullable=True),
    sa.Column('communication_city', sa.String(length=50), nullable=True),
    sa.Column('communication_state', sa.String(length=50), nullable=True),
    sa.Column('communication_pincode', sa.String(length=6), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('previous_insurance_experience', sa.Boolean(), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('previous_company_name', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=18), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('nominee_name', sa.String(length=100), nullable=True),
    sa.Column('nominee_relationship', sa.String(length=50), nullable=True),
    sa.Column('nominee_date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('territory_preference', sa.String(length=100), nullable=True),
    sa.Column('agent_code', sa.String(length=8), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_agent_code'), 'user_profiles', ['agent_code'], unique=True)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.create_table('cut_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('child_id_request_id', sa.UUID(), nullable=True),
    sa.Column('agent_code', sa.String(length=50), nullable=True),
    sa.Column('insurer_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('admin_child_id', sa.String(length=50), nullable=True),
    sa.Column('additional_documents', sa.Text(), nullable=True),
    sa.Column('policy_pdf_url', sa.Text(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('policy_start_date', sa.Date(), nullable=True),
    sa.Column('policy_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['admin_child_id'], ['admin_child_ids.child_id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['child_id_request_id'], ['child_id_requests.id'], ),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('agent_code', sa.String(length=50), nullable=True),
    sa.Column('additional_documents', sa.Text(), nullable=True),
    sa.Column('policy_pdf_url', sa.Text(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('policy_start_date', sa.Date(), nullable=True),
    sa.Column('policy_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_id_requests.child_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('cut_pay')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_agent_code'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index(op.f('ix_reconciliation_reports_insurer_name'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_insurer_code'), table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_processed_by', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_insurer_code', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_insurer', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_created_at', table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.drop_index(op.f('ix_cutpay_agent_configs_agent_code'), table_name='cutpay_agent_configs')
    op.drop_index('idx_cutpay_agent_config_date', table_name='cutpay_agent_configs')
    op.drop_index('idx_cutpay_agent_config_agent_code', table_name='cutpay_agent_configs')
    op.drop_table('cutpay_agent_configs')
    op.drop_index(op.f('ix_child_id_requests_user_id'), table_name='child_id_requests')
    op.drop_index(op.f('ix_child_id_requests_child_id'), table_name='child_id_requests')
    op.drop_table('child_id_requests')
    op.drop_index(op.f('ix_admin_child_ids_id'), table_name='admin_child_ids')
    op.drop_index(op.f('ix_admin_child_ids_child_id'), table_name='admin_child_ids')
    op.drop_table('admin_child_ids')
    op.drop_table('users')
    op.drop_index(op.f('ix_insurers_insurer_code'), table_name='insurers')
    op.drop_index(op.f('ix_insurers_id'), table_name='insurers')
    op.drop_table('insurers')
    op.drop_index(op.f('ix_brokers_id'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_broker_code'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
