"""rmeoved status

Revision ID: 2d28dd990519
Revises: d4db66e83865
Create Date: 2025-07-06 17:54:37.284536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d28dd990519"
down_revision: Union[str, None] = "d4db66e83865"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cut_pay", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cut_pay",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
