"""Add CutPay agent configuration model

Revision ID: 30040a00ef55
Revises: f66881fe17f9
Create Date: 2025-07-13 20:54:55.886398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30040a00ef55'
down_revision: Union[str, None] = 'f66881fe17f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutpay_agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_code', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=100), nullable=False),
    sa.Column('payment_mode_detail', sa.Text(), nullable=True),
    sa.Column('po_paid_to_agent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code', 'date', name='unique_cutpay_agent_config_per_date')
    )
    op.create_index('idx_cutpay_agent_config_agent_code', 'cutpay_agent_configs', ['agent_code'], unique=False)
    op.create_index('idx_cutpay_agent_config_date', 'cutpay_agent_configs', ['date'], unique=False)
    op.create_index(op.f('ix_cutpay_agent_configs_agent_code'), 'cutpay_agent_configs', ['agent_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cutpay_agent_configs_agent_code'), table_name='cutpay_agent_configs')
    op.drop_index('idx_cutpay_agent_config_date', table_name='cutpay_agent_configs')
    op.drop_index('idx_cutpay_agent_config_agent_code', table_name='cutpay_agent_configs')
    op.drop_table('cutpay_agent_configs')
    # ### end Alembic commands ###
