"""total po removed from cutpay model

Revision ID: 3a1a56a6359a
Revises: 4db12a1eea08
Create Date: 2025-11-15 19:27:56.214427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1a56a6359a'
down_revision: Union[str, None] = '4db12a1eea08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cut_pay', 'agent_total_po_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('agent_total_po_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
