"""User profile and document

Revision ID: 3aee03cdc3a7
Revises: 
Create Date: 2025-06-17 17:02:38.001505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aee03cdc3a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=15), nullable=True),
    sa.Column('alternate_email', sa.String(length=255), nullable=True),
    sa.Column('permanent_address_line1', sa.String(length=200), nullable=True),
    sa.Column('permanent_address_line2', sa.String(length=200), nullable=True),
    sa.Column('permanent_city', sa.String(length=50), nullable=True),
    sa.Column('permanent_state', sa.String(length=50), nullable=True),
    sa.Column('permanent_pincode', sa.String(length=6), nullable=True),
    sa.Column('communication_same_as_permanent', sa.Boolean(), nullable=True),
    sa.Column('communication_address_line1', sa.String(length=200), nullable=True),
    sa.Column('communication_address_line2', sa.String(length=200), nullable=True),
    sa.Column('communication_city', sa.String(length=50), nullable=True),
    sa.Column('communication_state', sa.String(length=50), nullable=True),
    sa.Column('communication_pincode', sa.String(length=6), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('previous_insurance_experience', sa.Boolean(), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('previous_company_name', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=18), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('nominee_name', sa.String(length=100), nullable=True),
    sa.Column('nominee_relationship', sa.String(length=50), nullable=True),
    sa.Column('nominee_date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('territory_preference', sa.String(length=100), nullable=True),
    sa.Column('agent_code', sa.String(length=8), nullable=True),
    sa.Column('registration_status', sa.String(length=20), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_agent_code'), 'user_profiles', ['agent_code'], unique=True)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_agent_code'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_table('user_documents')
    # ### end Alembic commands ###
