"""removed aadhar and pan

Revision ID: 429172fc3954
Revises: a98519992fe1
Create Date: 2025-06-18 16:21:41.705234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429172fc3954'
down_revision: Union[str, None] = 'a98519992fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profiles_aadhaar_number_key', 'user_profiles', type_='unique')
    op.drop_constraint('user_profiles_pan_number_key', 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'pan_number')
    op.drop_column('user_profiles', 'aadhaar_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('aadhaar_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('pan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_profiles_pan_number_key', 'user_profiles', ['pan_number'])
    op.create_unique_constraint('user_profiles_aadhaar_number_key', 'user_profiles', ['aadhaar_number'])
    # ### end Alembic commands ###
