"""add_policy_table

Revision ID: 49378e4d21b5
Revises: 49959fd36796
Create Date: 2025-06-19 13:33:39.106025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49378e4d21b5'
down_revision: Union[str, None] = '49959fd36796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_code', sa.String(length=50), nullable=True),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('broker_name', sa.String(length=200), nullable=True),
    sa.Column('insurance_company', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_class', sa.String(length=50), nullable=True),
    sa.Column('vehicle_segment', sa.String(length=50), nullable=True),
    sa.Column('gross_premium', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_premium', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('od_premium', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tp_premium', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=500), nullable=False),
    sa.Column('pdf_file_name', sa.String(length=255), nullable=False),
    sa.Column('ai_extracted_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['user_profiles.user_id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child_id_requests.child_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
