"""remove_payment_status_from_cutpay

Revision ID: 49959fd36796
Revises: 429172fc3954
Create Date: 2025-06-18 20:35:24.271190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49959fd36796'
down_revision: Union[str, None] = '429172fc3954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cut_pay', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
