"""change cutpay_received to float

Revision ID: 4be501a2aae8
Revises: 9710399d1024
Create Date: 2025-07-19 04:26:47.961368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4be501a2aae8"
down_revision: Union[str, None] = "9710399d1024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually handle type conversion with USING clause for PostgreSQL
    op.execute(
        """
        ALTER TABLE cut_pay 
        ALTER COLUMN cutpay_received 
        TYPE NUMERIC(15, 2) 
        USING CASE 
            WHEN cutpay_received IS NULL OR cutpay_received = '' THEN NULL 
            WHEN cutpay_received ~ '^[0-9]+\.?[0-9]*$' THEN cutpay_received::numeric
            ELSE NULL
        END
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually handle type conversion with USING clause for PostgreSQL
    op.execute(
        """
        ALTER TABLE cut_pay 
        ALTER COLUMN cutpay_received 
        TYPE VARCHAR(10) 
        USING cutpay_received::text
    """
    )
    # ### end Alembic commands ###
