"""two fields added in cutpay

Revision ID: 4db12a1eea08
Revises: 26b2701970ce
Create Date: 2025-11-15 18:59:26.346775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db12a1eea08'
down_revision: Union[str, None] = '26b2701970ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('agent_total_po_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('cut_pay_amount_received', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cut_pay', 'cut_pay_amount_received')
    op.drop_column('cut_pay', 'agent_total_po_amount')
    # ### end Alembic commands ###
