"""Add cutpay fields to policy model and match status support

Revision ID: 5c358e180374
Revises: 673d013153a9
Create Date: 2025-07-29 23:45:29.622446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c358e180374'
down_revision: Union[str, None] = '673d013153a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('formatted_policy_number', sa.String(length=100), nullable=True))
    op.add_column('policies', sa.Column('major_categorisation', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('product_insurer_report', sa.String(length=200), nullable=True))
    op.add_column('policies', sa.Column('product_type', sa.String(length=100), nullable=True))
    op.add_column('policies', sa.Column('plan_type', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('policies', sa.Column('customer_phone_number', sa.String(length=20), nullable=True))
    op.add_column('policies', sa.Column('registration_no', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('make_model', sa.String(length=100), nullable=True))
    op.add_column('policies', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('policies', sa.Column('vehicle_variant', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('gvw', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('policies', sa.Column('rto', sa.String(length=20), nullable=True))
    op.add_column('policies', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('fuel_type', sa.String(length=20), nullable=True))
    op.add_column('policies', sa.Column('cc', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('age_year', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('ncb', sa.String(length=10), nullable=True))
    op.add_column('policies', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('policies', sa.Column('business_type', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('seating_capacity', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('veh_wheels', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('gst_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('policies', sa.Column('agent_commission_given_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('policies', sa.Column('agent_extra_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('policies', sa.Column('code_type', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('payment_by', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('policies', sa.Column('cluster', sa.String(length=50), nullable=True))
    op.add_column('policies', sa.Column('is_private_car', sa.Boolean(), nullable=True))
    op.add_column('policies', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'notes')
    op.drop_column('policies', 'is_private_car')
    op.drop_column('policies', 'cluster')
    op.drop_column('policies', 'payment_method')
    op.drop_column('policies', 'payment_by')
    op.drop_column('policies', 'code_type')
    op.drop_column('policies', 'agent_extra_percent')
    op.drop_column('policies', 'agent_commission_given_percent')
    op.drop_column('policies', 'gst_amount')
    op.drop_column('policies', 'veh_wheels')
    op.drop_column('policies', 'seating_capacity')
    op.drop_column('policies', 'business_type')
    op.drop_column('policies', 'discount_percent')
    op.drop_column('policies', 'ncb')
    op.drop_column('policies', 'age_year')
    op.drop_column('policies', 'cc')
    op.drop_column('policies', 'fuel_type')
    op.drop_column('policies', 'state')
    op.drop_column('policies', 'rto')
    op.drop_column('policies', 'gvw')
    op.drop_column('policies', 'vehicle_variant')
    op.drop_column('policies', 'model')
    op.drop_column('policies', 'make_model')
    op.drop_column('policies', 'registration_no')
    op.drop_column('policies', 'customer_phone_number')
    op.drop_column('policies', 'customer_name')
    op.drop_column('policies', 'plan_type')
    op.drop_column('policies', 'product_type')
    op.drop_column('policies', 'product_insurer_report')
    op.drop_column('policies', 'major_categorisation')
    op.drop_column('policies', 'formatted_policy_number')
    # ### end Alembic commands ###
