"""remove_is_private_car_field_from_policies

Revision ID: 5cba5bda15b0
Revises: change_registration_no
Create Date: 2025-08-16 00:21:32.838554

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5cba5bda15b0"
down_revision: Union[str, None] = "change_registration_no"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
