"""add_number_of_policies_to_user_profile

Revision ID: 673d013153a9
Revises: 87528805b7b5
Create Date: 2025-07-23 23:28:47.650829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "673d013153a9"
down_revision: Union[str, None] = "87528805b7b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policies",
        sa.Column(
            "payment_by_office", sa.Numeric(precision=15, scale=2), nullable=True
        ),
    )
    op.add_column(
        "policies",
        sa.Column(
            "total_agent_payout_amount",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "user_profiles", sa.Column("number_of_policies", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "number_of_policies")
    op.drop_column("policies", "total_agent_payout_amount")
    op.drop_column("policies", "payment_by_office")
    # ### end Alembic commands ###
