"""Add post-cutpay details fields

Revision ID: 72936f6080e8
Revises: 30040a00ef55
Create Date: 2025-07-14 01:24:17.547966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72936f6080e8"
down_revision: Union[str, None] = "30040a00ef55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cut_pay",
        sa.Column(
            "already_given_to_agent", sa.Numeric(precision=15, scale=2), nullable=True
        ),
    )
    op.add_column(
        "cut_pay",
        sa.Column(
            "iz_total_po_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
    )
    op.add_column(
        "cut_pay",
        sa.Column("broker_po_percent", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "cut_pay",
        sa.Column(
            "broker_payout_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
    )
    op.add_column(
        "cut_pay", sa.Column("invoice_status", sa.String(length=50), nullable=True)
    )
    op.add_column("cut_pay", sa.Column("remarks", sa.Text(), nullable=True))
    op.add_column("cut_pay", sa.Column("company", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cut_pay", "company")
    op.drop_column("cut_pay", "remarks")
    op.drop_column("cut_pay", "invoice_status")
    op.drop_column("cut_pay", "broker_payout_amount")
    op.drop_column("cut_pay", "broker_po_percent")
    op.drop_column("cut_pay", "iz_total_po_percent")
    op.drop_column("cut_pay", "already_given_to_agent")
    # ### end Alembic commands ###
