"""rmoeved extra field

Revision ID: 860543ed4b27
Revises: c08fbf39cf96
Create Date: 2025-08-01 17:46:44.429813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "860543ed4b27"
down_revision: Union[str, None] = "c08fbf39cf96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policies", "registration_no")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policies",
        sa.Column(
            "registration_no", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
