"""add_agent_financial_tracking

Revision ID: 87528805b7b5
Revises: 6b7a2ac522b0
Create Date: 2025-07-23 19:18:09.791259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87528805b7b5"
down_revision: Union[str, None] = "6b7a2ac522b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_child_ids", sa.Column("password", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "child_id_requests", sa.Column("password", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user_profiles",
        sa.Column("running_balance", sa.Numeric(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "total_net_premium", sa.Numeric(precision=15, scale=2), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "total_net_premium")
    op.drop_column("user_profiles", "running_balance")
    op.drop_column("child_id_requests", "password")
    op.drop_column("admin_child_ids", "password")
    # ### end Alembic commands ###
