"""child id

Revision ID: 91cec648e58a
Revises: 3aee03cdc3a7
Create Date: 2025-06-17 22:39:40.031033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cec648e58a'
down_revision: Union[str, None] = '3aee03cdc3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_id_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insurance_company', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_rm_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('broker_code', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('commission_percentage', sa.Float(), nullable=True),
    sa.Column('policy_limit', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_id_requests_child_id'), 'child_id_requests', ['child_id'], unique=True)
    op.create_index(op.f('ix_child_id_requests_user_id'), 'child_id_requests', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('user_role', sa.String(length=20), nullable=False))
    op.drop_column('user_profiles', 'registration_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('registration_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'user_role')
    op.drop_index(op.f('ix_child_id_requests_user_id'), table_name='child_id_requests')
    op.drop_index(op.f('ix_child_id_requests_child_id'), table_name='child_id_requests')
    op.drop_table('child_id_requests')
    # ### end Alembic commands ###
