"""payment from office is now a float

Revision ID: 9710399d1024
Revises: 652e7a2380e6
Create Date: 2025-07-19 04:04:35.329655

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9710399d1024"
down_revision: Union[str, None] = "652e7a2380e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually handle type conversion with USING clause for PostgreSQL
    op.execute(
        """
        ALTER TABLE cut_pay 
        ALTER COLUMN payment_by_office 
        TYPE NUMERIC(15, 2) 
        USING CASE 
            WHEN payment_by_office IS NULL OR payment_by_office = '' THEN NULL 
            ELSE payment_by_office::numeric 
        END
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually handle type conversion with USING clause for PostgreSQL
    op.execute(
        """
        ALTER TABLE cut_pay 
        ALTER COLUMN payment_by_office 
        TYPE VARCHAR(50) 
        USING payment_by_office::text
    """
    )
    # ### end Alembic commands ###
