"""cut pay

Revision ID: a98519992fe1
Revises: 91cec648e58a
Create Date: 2025-06-18 15:56:08.212456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98519992fe1'
down_revision: Union[str, None] = '91cec648e58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('agent_code', sa.String(length=50), nullable=False),
    sa.Column('insurance_company', sa.String(length=200), nullable=False),
    sa.Column('broker', sa.String(length=200), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_premium', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission_grid', sa.String(length=100), nullable=False),
    sa.Column('agent_commission_given_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cut_pay_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_by', sa.String(length=200), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('payment_source', sa.String(length=200), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cut_pay')
    # ### end Alembic commands ###
