"""Add reconciliation_reports table

Revision ID: c08fbf39cf96
Revises: 5c358e180374
Create Date: 2025-08-01 15:33:51.706991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c08fbf39cf96'
down_revision: Union[str, None] = '5c358e180374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurer_name', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('total_records_processed', sa.Integer(), nullable=False),
    sa.Column('total_records_updated', sa.Integer(), nullable=False),
    sa.Column('total_records_added', sa.Integer(), nullable=False),
    sa.Column('total_records_skipped', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('processing_time_seconds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('data_variance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('coverage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('field_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reconciliation_reports_created_at', 'reconciliation_reports', ['created_at'], unique=False)
    op.create_index('idx_reconciliation_reports_insurer', 'reconciliation_reports', ['insurer_name'], unique=False)
    op.create_index('idx_reconciliation_reports_processed_by', 'reconciliation_reports', ['processed_by'], unique=False)
    op.create_index('idx_reconciliation_reports_status', 'reconciliation_reports', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_insurer_name'), 'reconciliation_reports', ['insurer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_reports_insurer_name'), table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_status', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_processed_by', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_insurer', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_created_at', table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    # ### end Alembic commands ###
