"""init commit

Revision ID: d4db66e83865
Revises: 610039aa3bd5
Create Date: 2025-07-06 16:59:15.592798

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4db66e83865"
down_revision: Union[str, None] = "610039aa3bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cut_pay",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_pdf_url", sa.String(length=500), nullable=True),
        sa.Column(
            "additional_documents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column("formatted_policy_number", sa.String(length=100), nullable=True),
        sa.Column("major_categorisation", sa.String(length=50), nullable=True),
        sa.Column("product_insurer_report", sa.String(length=200), nullable=True),
        sa.Column("product_type", sa.String(length=100), nullable=True),
        sa.Column("plan_type", sa.String(length=50), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("gross_premium", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("net_premium", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("od_premium", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("tp_premium", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("gst_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("registration_no", sa.String(length=50), nullable=True),
        sa.Column("make_model", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("vehicle_variant", sa.String(length=50), nullable=True),
        sa.Column("gvw", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("rto", sa.String(length=20), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("fuel_type", sa.String(length=20), nullable=True),
        sa.Column("cc", sa.Integer(), nullable=True),
        sa.Column("age_year", sa.Integer(), nullable=True),
        sa.Column("ncb", sa.String(length=10), nullable=True),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("business_type", sa.String(length=50), nullable=True),
        sa.Column("seating_capacity", sa.Integer(), nullable=True),
        sa.Column("veh_wheels", sa.Integer(), nullable=True),
        sa.Column("reporting_month", sa.String(length=10), nullable=True),
        sa.Column("booking_date", sa.Date(), nullable=True),
        sa.Column("agent_code", sa.String(length=50), nullable=True),
        sa.Column("code_type", sa.String(length=50), nullable=True),
        sa.Column(
            "incoming_grid_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "agent_commission_given_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("extra_grid", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "commissionable_premium", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("payment_by", sa.String(length=50), nullable=True),
        sa.Column("payment_method", sa.String(length=100), nullable=True),
        sa.Column("payout_on", sa.String(length=20), nullable=True),
        sa.Column(
            "agent_extra_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("payment_by_office", sa.String(length=50), nullable=True),
        sa.Column("insurer_id", sa.Integer(), nullable=True),
        sa.Column("broker_id", sa.Integer(), nullable=True),
        sa.Column("child_id_request_id", sa.UUID(), nullable=True),
        sa.Column("admin_child_id", sa.String(length=50), nullable=True),
        sa.Column("insurer_name", sa.String(length=200), nullable=True),
        sa.Column("broker_name", sa.String(length=200), nullable=True),
        sa.Column("insurer_broker_code", sa.String(length=100), nullable=True),
        sa.Column("cluster", sa.String(length=50), nullable=True),
        sa.Column(
            "receivable_from_broker", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "extra_amount_receivable_from_broker",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "total_receivable_from_broker",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column(
            "total_receivable_from_broker_with_gst",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
        ),
        sa.Column("cut_pay_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("agent_po_amt", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "agent_extra_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "total_agent_po_amt", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("claimed_by", sa.String(length=200), nullable=True),
        sa.Column(
            "already_given_to_agent", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("po_paid_to_agent", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("running_bal", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("match_status", sa.String(length=50), nullable=True),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("synced_to_cutpay_sheet", sa.Boolean(), nullable=False),
        sa.Column("synced_to_master_sheet", sa.Boolean(), nullable=False),
        sa.Column("cutpay_sheet_row_id", sa.String(length=50), nullable=True),
        sa.Column("master_sheet_row_id", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_child_id"],
            ["admin_child_ids.child_id"],
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["brokers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id_request_id"],
            ["child_id_requests.id"],
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["insurer_id"],
            ["insurers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cut_pay")
    # ### end Alembic commands ###
