"""changed

Revision ID: e95d78f169f7
Revises: 76797fe43e17
Create Date: 2025-07-06 01:27:35.681360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95d78f169f7'
down_revision: Union[str, None] = '76797fe43e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_id_requests', sa.Column('insurer_code', sa.String(length=10), nullable=False))
    op.add_column('child_id_requests', sa.Column('broker_code', sa.String(length=10), nullable=True))
    op.drop_constraint('child_id_requests_broker_id_fkey', 'child_id_requests', type_='foreignkey')
    op.drop_constraint('child_id_requests_insurer_id_fkey', 'child_id_requests', type_='foreignkey')
    op.create_foreign_key(None, 'child_id_requests', 'brokers', ['broker_code'], ['broker_code'])
    op.create_foreign_key(None, 'child_id_requests', 'insurers', ['insurer_code'], ['insurer_code'])
    op.drop_column('child_id_requests', 'broker_id')
    op.drop_column('child_id_requests', 'insurer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_id_requests', sa.Column('insurer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('child_id_requests', sa.Column('broker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'child_id_requests', type_='foreignkey')
    op.drop_constraint(None, 'child_id_requests', type_='foreignkey')
    op.create_foreign_key('child_id_requests_insurer_id_fkey', 'child_id_requests', 'insurers', ['insurer_id'], ['id'])
    op.create_foreign_key('child_id_requests_broker_id_fkey', 'child_id_requests', 'brokers', ['broker_id'], ['id'])
    op.drop_column('child_id_requests', 'broker_code')
    op.drop_column('child_id_requests', 'insurer_code')
    # ### end Alembic commands ###
