"""admin child ids

Revision ID: ebeaf48ba4cc
Revises: 07db71c72ff0
Create Date: 2025-07-05 21:29:49.622615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebeaf48ba4cc'
down_revision: Union[str, None] = '07db71c72ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('admin_child_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cut_pay', 'admin_child_ids', ['admin_child_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cut_pay', type_='foreignkey')
    op.drop_column('cut_pay', 'admin_child_id')
    # ### end Alembic commands ###
