"""update_cutpay_model_for_new_flow

Revision ID: f17eb6a061b8
Revises: f7042c6405fe
Create Date: 2025-06-27 00:44:43.111548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f17eb6a061b8'
down_revision: Union[str, None] = 'f7042c6405fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('policy_pdf_url', sa.String(length=500), nullable=True))
    op.add_column('cut_pay', sa.Column('additional_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cut_pay', sa.Column('policy_holder_name', sa.String(length=200), nullable=True))
    op.add_column('cut_pay', sa.Column('policy_start_date', sa.Date(), nullable=True))
    op.add_column('cut_pay', sa.Column('policy_end_date', sa.Date(), nullable=True))
    op.add_column('cut_pay', sa.Column('premium_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('sum_insured', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('insurance_type', sa.String(length=100), nullable=True))
    op.add_column('cut_pay', sa.Column('code_type', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('insurer_id', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('broker_id', sa.Integer(), nullable=True))
    op.add_column('cut_pay', sa.Column('child_id_request_id', postgresql.UUID(), nullable=True))
    op.add_column('cut_pay', sa.Column('payment_mode', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('payout_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cut_pay', sa.Column('payout_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    
    # Add status column as nullable first, then update existing records and make it NOT NULL
    op.add_column('cut_pay', sa.Column('status', sa.String(length=50), nullable=True))
    
    # Add boolean columns with default values
    op.add_column('cut_pay', sa.Column('synced_to_cutpay_sheet', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('cut_pay', sa.Column('synced_to_master_sheet', sa.Boolean(), nullable=True, server_default='false'))
    
    op.add_column('cut_pay', sa.Column('cutpay_sheet_row_id', sa.String(length=50), nullable=True))
    op.add_column('cut_pay', sa.Column('master_sheet_row_id', sa.String(length=50), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE cut_pay SET status = 'completed' WHERE status IS NULL")
    op.execute("UPDATE cut_pay SET synced_to_cutpay_sheet = false WHERE synced_to_cutpay_sheet IS NULL")
    op.execute("UPDATE cut_pay SET synced_to_master_sheet = false WHERE synced_to_master_sheet IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('cut_pay', 'status', nullable=False)
    op.alter_column('cut_pay', 'synced_to_cutpay_sheet', nullable=False, server_default=None)
    op.alter_column('cut_pay', 'synced_to_master_sheet', nullable=False, server_default=None)
    op.alter_column('cut_pay', 'policy_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cut_pay', 'agent_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cut_pay', 'gross_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('cut_pay', 'net_premium',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('cut_pay', 'commission_grid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cut_pay', 'agent_commission_given_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('cut_pay', 'cut_pay_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('cut_pay', 'payment_by',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cut_pay', 'amount_received',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('cut_pay', 'payment_method',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cut_pay', 'payment_source',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cut_pay', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'cut_pay', 'child_id_requests', ['child_id_request_id'], ['id'])
    op.create_foreign_key(None, 'cut_pay', 'insurers', ['insurer_id'], ['id'])
    op.create_foreign_key(None, 'cut_pay', 'brokers', ['broker_id'], ['id'])
    op.drop_column('cut_pay', 'insurance_company')
    op.drop_column('cut_pay', 'broker')
    op.create_foreign_key(None, 'policies', 'child_id_requests', ['child_id'], ['child_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.add_column('cut_pay', sa.Column('broker', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('cut_pay', sa.Column('insurance_company', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cut_pay', type_='foreignkey')
    op.drop_constraint(None, 'cut_pay', type_='foreignkey')
    op.drop_constraint(None, 'cut_pay', type_='foreignkey')
    op.alter_column('cut_pay', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('cut_pay', 'payment_source',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cut_pay', 'payment_method',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cut_pay', 'amount_received',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('cut_pay', 'payment_by',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cut_pay', 'cut_pay_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('cut_pay', 'agent_commission_given_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('cut_pay', 'commission_grid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cut_pay', 'net_premium',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('cut_pay', 'gross_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('cut_pay', 'agent_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cut_pay', 'policy_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('cut_pay', 'master_sheet_row_id')
    op.drop_column('cut_pay', 'cutpay_sheet_row_id')
    op.drop_column('cut_pay', 'synced_to_master_sheet')
    op.drop_column('cut_pay', 'synced_to_cutpay_sheet')
    op.drop_column('cut_pay', 'status')
    op.drop_column('cut_pay', 'payout_amount')
    op.drop_column('cut_pay', 'payout_percent')
    op.drop_column('cut_pay', 'payment_mode')
    op.drop_column('cut_pay', 'child_id_request_id')
    op.drop_column('cut_pay', 'broker_id')
    op.drop_column('cut_pay', 'insurer_id')
    op.drop_column('cut_pay', 'code_type')
    op.drop_column('cut_pay', 'insurance_type')
    op.drop_column('cut_pay', 'sum_insured')
    op.drop_column('cut_pay', 'premium_amount')
    op.drop_column('cut_pay', 'policy_end_date')
    op.drop_column('cut_pay', 'policy_start_date')
    op.drop_column('cut_pay', 'policy_holder_name')
    op.drop_column('cut_pay', 'additional_documents')
    op.drop_column('cut_pay', 'policy_pdf_url')
    # ### end Alembic commands ###
