"""Update CutPay model for cutpay improvements

Revision ID: f66881fe17f9
Revises: 2d28dd990519
Create Date: 2025-07-13 20:05:53.680943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66881fe17f9'
down_revision: Union[str, None] = '2d28dd990519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('customer_phone_number', sa.String(length=20), nullable=True))
    op.add_column('cut_pay', sa.Column('cutpay_received', sa.String(length=10), nullable=True))
    op.drop_column('cut_pay', 'invoice_number')
    op.drop_column('cut_pay', 'match_status')
    op.drop_column('cut_pay', 'already_given_to_agent')
    op.drop_column('cut_pay', 'po_paid_to_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('po_paid_to_agent', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('cut_pay', sa.Column('already_given_to_agent', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('cut_pay', sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cut_pay', sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('cut_pay', 'cutpay_received')
    op.drop_column('cut_pay', 'customer_phone_number')
    # ### end Alembic commands ###
