"""added admin child is table and updated child id table

Revision ID: f7042c6405fe
Revises: 6c6b7304cd46
Create Date: 2025-06-26 17:03:29.535413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7042c6405fe'
down_revision: Union[str, None] = '6c6b7304cd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('rm', sa.String(length=100), nullable=False),
    sa.Column('gst', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_broker_code'), 'brokers', ['broker_code'], unique=True)
    op.create_index(op.f('ix_brokers_id'), 'brokers', ['id'], unique=False)
    op.create_table('insurers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurers_id'), 'insurers', ['id'], unique=False)
    op.create_index(op.f('ix_insurers_insurer_code'), 'insurers', ['insurer_code'], unique=True)
    op.create_table('admin_child_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_child_ids_child_id'), 'admin_child_ids', ['child_id'], unique=True)
    op.create_index(op.f('ix_admin_child_ids_id'), 'admin_child_ids', ['id'], unique=False)
    
    # Recreate child_id_requests table with new structure
    op.create_table('child_id_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('insurer_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('preferred_rm_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_id_requests_child_id'), 'child_id_requests', ['child_id'], unique=True)
    op.create_index(op.f('ix_child_id_requests_user_id'), 'child_id_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the recreated child_id_requests table
    op.drop_index(op.f('ix_child_id_requests_user_id'), table_name='child_id_requests')
    op.drop_index(op.f('ix_child_id_requests_child_id'), table_name='child_id_requests')
    op.drop_table('child_id_requests')
    
    # Drop new tables
    op.drop_index(op.f('ix_admin_child_ids_id'), table_name='admin_child_ids')
    op.drop_index(op.f('ix_admin_child_ids_child_id'), table_name='admin_child_ids')
    op.drop_table('admin_child_ids')
    op.drop_index(op.f('ix_insurers_insurer_code'), table_name='insurers')
    op.drop_index(op.f('ix_insurers_id'), table_name='insurers')
    op.drop_table('insurers')
    op.drop_index(op.f('ix_brokers_broker_code'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_id'), table_name='brokers')
    op.drop_table('brokers')
    
    # Recreate original child_id_requests table structure
    op.create_table('child_id_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insurance_company', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_rm_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.String(length=50), nullable=True),
    sa.Column('broker_code', sa.String(length=20), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('commission_percentage', sa.Float(), nullable=True),
    sa.Column('policy_limit', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_id_requests_child_id'), 'child_id_requests', ['child_id'], unique=True)
    op.create_index(op.f('ix_child_id_requests_user_id'), 'child_id_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###
    op.drop_table('insurers')
    op.drop_index(op.f('ix_brokers_id'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_broker_code'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
