"""sync models with database state

Revision ID: fad68cc96e94
Revises: ed95261f0278
Create Date: 2025-08-31 17:13:16.854493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fad68cc96e94"
down_revision: Union[str, None] = "ed95261f0278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cut_pay", sa.Column("additional_documents", sa.Text(), nullable=True)
    )
    op.add_column("cut_pay", sa.Column("policy_pdf_url", sa.Text(), nullable=True))
    op.drop_column("cut_pay", "vehicle_documents_url")
    op.drop_column("cut_pay", "customer_documents_url")
    op.drop_column("cut_pay", "policy_documents_url")
    op.add_column(
        "policies", sa.Column("additional_documents", sa.Text(), nullable=True)
    )
    op.add_column("policies", sa.Column("policy_pdf_url", sa.Text(), nullable=True))
    op.drop_column("policies", "vehicle_documents_url")
    op.drop_column("policies", "customer_documents_url")
    op.drop_column("policies", "policy_documents_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policies",
        sa.Column(
            "policy_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "policies",
        sa.Column(
            "customer_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "policies",
        sa.Column(
            "vehicle_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("policies", "policy_pdf_url")
    op.drop_column("policies", "additional_documents")
    op.add_column(
        "cut_pay",
        sa.Column(
            "policy_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cut_pay",
        sa.Column(
            "customer_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cut_pay",
        sa.Column(
            "vehicle_documents_url", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("cut_pay", "policy_pdf_url")
    op.drop_column("cut_pay", "additional_documents")
    # ### end Alembic commands ###
