"""changed registration number

Revision ID: ff8fe434d15c
Revises: 23dbe9ec64db
Create Date: 2025-08-09 00:14:53.817421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8fe434d15c'
down_revision: Union[str, None] = '23dbe9ec64db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.drop_column('cut_pay', 'registration_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_pay', sa.Column('registration_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('cut_pay', 'registration_number')

